# Migrate from Container registry to Artifact registry

name: Deploy Docker to GCE

on:
  push:
    branches:
    - main
  
env:
  PROJECT_ID: manu-twitter-bot
  GCE_INSTANCE: twitter-bot
  GCE_INSTANCE_ZONE: us-east1-b

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - run: gcloud --quiet auth configure-docker us-east1-docker.pkg.dev
    
    - name: Add secrets to files and build
      run: |
        mkdir config
        echo "${{ secrets.GCP_CREDENTIALS }}" > config/google_creds.json
        echo "${{ secrets.CONFIG }}" > config/config.ini
        docker build --tag "us-east1-docker.pkg.dev/$PROJECT_ID/$GCE_INSTANCE/bot:$GITHUB_SHA" .

    - name: Push
      run: docker push "us-east1-docker.pkg.dev/$PROJECT_ID/$GCE_INSTANCE/bot:$GITHUB_SHA"

    - name: Update GCE
      run: |
        gcloud compute instances update-container "$GCE_INSTANCE" \
          --zone "$GCE_INSTANCE_ZONE" \
          --container-image "us-east1-docker.pkg.dev/$PROJECT_ID/$GCE_INSTANCE/bot:$GITHUB_SHA"